name: Deploy to Next Environment
run-name: Deploy to Next Environment
on: [push]
  name: Azure ARM
  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@adf_publish

        # Log into Azure
      - uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
        - name: data-factory-deploy
          uses: Azure/data-factory-deploy-action@v1.2.0
          with:  
          resourceGroupName: ${{ secrets.AZURE_RG }}
          dataFactoryName: ${{ secrets.ADF_FACTORYNAME }}
          armTemplateFile: ./CICDADFVenkat/ARMTemplateForFactory.json
